### ISSUE TITLE
Files with spaces in the path is not supported

### ISSUE THREAD

**Issue by tiksn** [cake-contrib/Cake.ProtobufTools#8]
I am trying to build ptoto file that contains spaces in the path (folder name).
Protoc method fails with following error message

> ../src/GRPC: No such file or directory

../src/GRPC is the initial part of the relative path (I tried also with absolute path, same issue) till the first space.

Tried to fork and create PR but CI fails (#7 )

**Comment by gep13** [comment]
@tiksn thank you for your help.

That failing CI build is actually nothing to do with the change that you have made.  This repository makes use of Cake.Recipe, which recently added a breaking change as a result of a breaking change in Cake itself.

As a result, this line:

https://github.com/cake-contrib/Cake.ProtobufTools/blob/master/tools/packages.config#L3

Will need to change to use, as a minimum, 0.28.0.  If you make this change in your PR, then I suspect that it will just work.  You should be able to test this out locally before pushing.

**Comment by MihaMarkic** [comment]
@gep13 I've updated tool to 0.28 but now appveyor is all red.

**Comment by gep13** [comment]
@MihaMarkic but now it is all green 😄 

AppVeyor was holding onto a cached version of the tools folder, which meant that it still had a old copy of Cake.  So I cleared the build cache folder, and this sorted it out.

A minor improvement here:

https://github.com/cake-contrib/Cake.ProtobufTools/blob/master/.appveyor.yml#L31

To include the packages.config file would help.

**Comment by tiksn** [comment]
Thanks, @gep13 now it works fine. Sorry for the late reply.

**Comment by gep13** [comment]
@tiksn you are very welcome 😄
